[package]
name = "sshelper-gui"
description = "sshelper graphical interface"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sshelper-gui"
path = "src/main.rs"

[dependencies]
eframe = "0.36.2"
egui-phosphor = "0.14.0"
sshelper-core = { path = "../sshelper-core" }

[dev-dependencies]
egui_kittest = { version = "0.36.2", features = ["eframe"] }
tempfile = "3.27.0"

[target."cfg(windows)".dependencies]
raw-window-handle = "0.6"

[build-dependencies]
winresource = "0.1.31"
